spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-254-120-2.eu-west-1.compute.amazonaws.com:5432/d53hcflfaqjv3k
    username: edpxqlvyisylor
    password: 42f18423bc84a8a14de56f6b0f85abd3b5ee56f1869df37583a9cc4787d1982b
    pool-size: 30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true