spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-74-156-137.eu-west-1.compute.amazonaws.com:5432/d35fh215a5e3lt
    username: ddzgmpatuvmrmc
    password: d830676496c7a60597bfbff9b6d9007a9057c22b81cce6dc9465aadd7040b6f2
    pool-size: 30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true